config/routes.rb
Rails.application.routes.draw do
  resources :menus
  root to: 'visitors#index'
  resources :roles do
    member do
      get 'edit_menus'
      post 'update_menus'
    end
  end
  resources :users do
    collection do
      get 'edit_profile'
      patch 'update_profile'
    end
  end
  devise_for :users, path: 'sessions'
end

app/models/menu.rb
class Menu < ApplicationRecord

  belongs_to :parent, class_name: 'Menu', optional: true
  has_many :submenus, class_name: 'Menu', foreign_key: 'parent_id'
  has_and_belongs_to_many :roles

  scope :roots, -> { where(parent_id: nil) }

  validates :label, presence: true
  validates :url, presence: true

  def name
    self.label
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!

  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.roots
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = params[:parent].blank? ? Menu.new : Menu.find(params[:parent]).submenus.build
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to menus_path, notice: t('message.success_created', model: Menu.model_name.human) }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to menus_path, notice: t('message.success_updated', :model => Menu.model_name.human) }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, t('message.success_destroyed', :model => Menu.model_name.human) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:label, :url, :parent_id)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.slim
= simple_form_for(@menu) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :label, required: true, placeholder: Menu.human_attribute_name(:label)
  = f.input :url, required: true, placeholder: Menu.human_attribute_name(:url)
  = f.association :parent

  .row.actions
    .col-sm.text-center
      = link_to menus_path, class: "btn btn-secondary" do
        i.fas.fa-arrow-circle-left.mr-2
        =I18n.t "button.back"
    .col-sm.text-center= f.submit class: 'btn btn-primary'

app/views/menus/_menu.html.slim
.list-group-item.node-treeview4 data-nodeid="#{menu.id}"
  - if menu.submenus.any?
    i.fas.fa-plus.mr-2
  - else
    i.fas.fa-minus.mr-2
  = menu.label
  =link_to edit_menu_path(menu), class: 'mx-1' do
    i.fas.fa-pencil-alt
  =link_to new_menu_path(parent: menu), class: 'mx-1' do
    i.fas.fa-plus-circle
  =link_to menu, class: 'mx-1', data: { confirm: I18n.t('message.confirm_delete') }, method: :delete do
    i.fas.fa-trash-alt
  - if menu.submenus.any?
    .list-group
      - menu.submenus.each do |submenu|
        = render submenu

app/views/menus/edit.html.slim
.card
  h5.card-header= I18n.t "title.edit", model: Menu.model_name.human
  .card-body
    == render 'form'

app/views/menus/index.html.slim
.card
  h5.card-header= Menu.model_name.human(count: 2)
  .card-body
    .row
      .col-sm
        = link_to new_menu_path, class: 'btn btn-primary' do
          i.fas.fa-pencil-alt.mr-2
          = I18n.t "button.new", model: Menu.model_name.human
    .row.my-2
      .col-sm
        #menus.treeview
          .list-group.list-group-root.well
            - @menus.each do |menu|
              = render menu

app/views/menus/new.html.slim
.card
  h5.card-header= I18n.t "title.new", model: Menu.model_name.human
  .card-body
    == render 'form'

app/views/menus/show.html.slim
p#notice = notice

p
  strong Label:
  = @menu.label
p
  strong Url:
  = @menu.url
p
  strong Parent:
  = @menu.parent

=> link_to 'Edit', edit_menu_path(@menu)
'|
=< link_to 'Back', menus_path