config/routes.rb
Rails.application.routes.draw do
  resources :menus
  root to: 'visitors#index'
  resources :roles do
    member do
      get 'edit_menus'
      post 'update_menus'
    end
  end
  resources :users do
    collection do
      get 'edit_profile'
      patch 'update_profile'
    end
  end
  devise_for :users, path: 'sessions'
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role

  validates :name, presence: true

  scope :search, ->(query) { where("name like :query or company like :query", query: "%#{query}%") }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user!

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @items = params[:per_page] || 10
    @query = params[:search]
    records = @query.blank? ? User.all : User.search(@query)
    @pagy, @users = pagy(records, items: @items)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # GET /users/edit_profile
  def edit_profile
    @user = current_user
  end

  # POST /users/update_profile
  def update_profile
    @user = current_user
    if @user.update(user_params.delete_if{|k,v| v.blank?})
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@user)
      redirect_to root_path, notice: t('message.success_updated', :model => User.model_name.human)
    else
      render "edit_profile"
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: t('message.success_created', model: User.model_name.human) }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

    respond_to do |format|
      if @user.update(user_params.delete_if{|k,v| v.blank?})
        format.html { redirect_to users_path, notice: t('message.success_updated', :model => User.model_name.human) }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: t('message.success_destroyed', :model => User.model_name.human) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :pasword_confirmation, :role_id, :company, :status)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= simple_form_for(@user, html: {class: 'form-horizontal'}) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :name, required: true, placeholder: User.human_attribute_name(:name)
  = f.input :email, required: true, placeholder: User.human_attribute_name(:email)
  = f.input :password
  = f.association :role
  = f.input :company
  = f.input :status

  .row.actions
    .col-sm.text-center
      = link_to users_path, class: "btn btn-secondary" do
        i.fas.fa-arrow-circle-left.mr-2
        =I18n.t "button.back"
    .col-sm.text-center= f.submit class: 'btn btn-primary'
    

app/views/users/edit.html.slim
.card
  h5.card-header= I18n.t "title.edit", model: User.model_name.human
  .card-body
    == render 'form'

app/views/users/edit_profile.html.slim
.card
  h5.card-header= I18n.t "title.edit", model: User.model_name.human
  .card-body
    = simple_form_for(@user, url: update_profile_users_path ) do |f|
      = f.error_notification
      = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

      = f.input :name, required: true, placeholder: User.human_attribute_name(:name)
      = f.input :email, required: true, placeholder: User.human_attribute_name(:email)
      = f.input :password
      = f.input :password_confirmation
      = f.association :role
      = f.input :company
      = f.input :status

      .row.actions
        .col-sm.text-center
          = link_to :back, class: "btn btn-secondary" do
            i.fas.fa-arrow-circle-left.mr-2
            =I18n.t "button.back"
        .col-sm.text-center= f.submit class: 'btn btn-primary'

app/views/users/index.html.slim
.card
  h5.card-header= User.model_name.human(count: 2)
  .card-body
    .row
      .col-sm
        = link_to new_user_path, class: 'btn btn-primary' do
          i.fas.fa-pencil-alt.mr-2
          = I18n.t "button.new", model: User.model_name.human
    .row.my-2
      .col-sm
        =form_tag users_path, method: :get, class: 'form-inline per_page'
          label.my-1.mr-2[for="per_page"]=I18n.t "label.show"
          = select_tag :per_page, options_for_select([1, 10, 25, 50, 100], @items), class: "custom-select my-1 mr-sm-2"
          label.my-1.mr-2=I18n.t "label.records"

      .col-sm
        =form_tag users_path, method: :get, class: 'form-inline search'
          label.col-sm-2.col-form-label[for="search"]= I18n.t "label.search"
          =search_field_tag :search, @query, class: 'form-control', placeholder: I18n.t("label.search")
    .row
      .col-sm
        table.table.table-striped
          thead
            tr
              th Id
              th= User.human_attribute_name(:name)
              th= User.human_attribute_name(:email)
              th= User.human_attribute_name(:created_at)
              th= User.human_attribute_name(:company)
              th= User.human_attribute_name(:status)
              th= User.human_attribute_name(:role)
              th= I18n.t "label.edit_delete"

          tbody
            - @users.each do |user|
              tr
                td = user.id
                td = user.name
                td = user.email
                td = I18n.l user.created_at.to_date, format: :long
                td = user.company
                td = user.status ? User.human_attribute_name("status.active") : User.human_attribute_name("status.inactive")
                td = user.role.try :name
                td
                  = link_to edit_user_path(user), class: 'mr-2' do
                    i.fas.fa-pencil-alt
                  = link_to user, data: { confirm: I18n.t('message.confirm_delete') }, method: :delete do
                    i.fas.fa-trash-alt
    .row
      .col-sm
        == pagy_info(@pagy)
    .row.justify-content-center
      .col-md-auto
        == pagy_bootstrap_nav(@pagy)

app/views/users/new.html.slim
.card
  h5.card-header= I18n.t "title.new", model: User.model_name.human
  .card-body
    == render 'form'

app/views/users/show.html.slim
p#notice = notice

p
  strong Name:
  = @user.name
p
  strong Email:
  = @user.email
p
  strong Password:
  = @user.password
p
  strong Pasword confirmation:
  = @user.pasword_confirmation
p
  strong Role:
  = @user.role
p
  strong Company:
  = @user.company
p
  strong Status:
  = @user.status

=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path