config/routes.rb
Rails.application.routes.draw do
  resources :menus
  root to: 'visitors#index'
  resources :roles do
    member do
      get 'edit_menus'
      post 'update_menus'
    end
  end
  resources :users do
    collection do
      get 'edit_profile'
      patch 'update_profile'
    end
  end
  devise_for :users, path: 'sessions'
end

app/models/role.rb
class Role < ApplicationRecord
  validates :name, presence: true

  scope :search, ->(query) { where("name like :query or description like :query", query: "%#{query}%") }

  has_many :users
  has_and_belongs_to_many :menus
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user!

  before_action :set_role, only: [:show, :edit, :update, :destroy, :edit_menus, :update_menus]

  # GET /roles
  # GET /roles.json
  def index
    @items = params[:per_page] || 10
    @query = params[:search]
    records = @query.blank? ? Role.all : Role.search(@query)
    @pagy, @roles = pagy(records, items: @items)
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # GET /roles/1/edit_menus
  def edit_menus
  end

  # POST /roles/1/update_menus
  def update_menus
    @role.menu_ids = params[:menus_ids]
    if @role.save
      redirect_to roles_path, notice: t('message.success_updated', :model => Role.model_name.human)
    else
      render 'edit_menus'
    end
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to roles_path, notice: t('message.success_created', model: Role.model_name.human) }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to roles_path, notice: t('message.success_updated', :model => Role.model_name.human) }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: t('message.success_destroyed', :model => Role.model_name.human) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
  include Pagy::Frontend
end

app/views/roles/_form.html.slim
= simple_form_for @role, html: {class: 'form-horizontal'} do |f|
  =f.error_notification

  = f.input :name, required: true, placeholder: Role.human_attribute_name(:name)
  = f.input :description, placeholder: Role.human_attribute_name(:description)
  .row.actions
    .col-sm.text-center
      = link_to roles_path, class: "btn btn-secondary" do
        i.fas.fa-arrow-circle-left.mr-2
        =I18n.t "button.back"
    .col-sm.text-center= f.submit class: 'btn btn-primary'

app/views/roles/_menu_form.html.slim
.list-group-item.node-treeview4.form-check
  =check_box_tag 'menus_ids[]', menu.id, @role.menu_ids.include?(menu.id), class: 'form-check-input'
  =label_tag menu.label, nil, class: 'form-check-label'

  .list-group
    - menu.submenus.each do |submenu|
        = render 'menu_form', menu: submenu

app/views/roles/edit.html.slim
.card
  h5.card-header= I18n.t "title.edit", model: Role.model_name.human
  .card-body
    == render 'form'

app/views/roles/edit_menus.html.slim
.card
  h5.card-header= Role.model_name.human(count: 2)
  .card-body
    .form-group
      label= Role.human_attribute_name(:name)
      input.form-control readonly=true value="#{@role.name}"

    h3= t '.edit_menus'

    = form_tag update_menus_role_path
      .list-group.list-group-root.well
        - Menu.roots.each do |menu|
          = render 'menu_form', menu: menu

      .row.actions
        .col-sm.text-center
          = link_to roles_path, class: "btn btn-secondary" do
            i.fas.fa-arrow-circle-left.mr-2
            =I18n.t "button.back"
        .col-sm.text-center= submit_tag I18n.t('button.save'), class: 'btn btn-primary'

app/views/roles/index.html.slim
.card
  h5.card-header= Role.model_name.human(count: 2)
  .card-body
    .row
      .col-sm
        = link_to new_role_path, class: 'btn btn-primary' do
          i.fas.fa-pencil-alt.mr-2
          = I18n.t "button.new", model: Role.model_name.human
    .row.my-2
      .col-sm
        =form_tag roles_path, method: :get, class: 'form-inline per_page'
          label.my-1.mr-2[for="per_page"]=I18n.t "label.show"
          = select_tag :per_page, options_for_select([1, 10, 25, 50, 100], @items), class: "custom-select my-1 mr-sm-2"
          label.my-1.mr-2=I18n.t "label.records"

      .col-sm
        =form_tag roles_path, method: :get, class: 'form-inline search'
          label.col-sm-2.col-form-label[for="search"]= I18n.t "label.search"
          =search_field_tag :search, @query, class: 'form-control', placeholder: I18n.t("label.search")
    .row
      .col-sm
        table.table.table-striped
          thead
            tr
              th Id
              th= Role.human_attribute_name(:name)
              th= Role.human_attribute_name(:description)
              th= I18n.t "label.edit_delete"

          tbody
            - @roles.each do |role|
              tr
                td = role.id
                td = role.name
                td = role.description
                td
                  = link_to edit_role_path(role), class: 'mr-2' do
                    i.fas.fa-pencil-alt
                  = link_to edit_menus_role_path(role), class: 'mr-2' do
                    i.fas.fa-th-list
                  = link_to role, data: { confirm: I18n.t('message.confirm_delete') }, method: :delete do
                    i.fas.fa-trash-alt
    .row
      .col-sm
        == pagy_info(@pagy)
    .row.justify-content-center
      .col-md-auto
        == pagy_bootstrap_nav(@pagy)

app/views/roles/new.html.slim
.card
  h5.card-header= I18n.t "title.new", model: Role.model_name.human
  .card-body
    == render 'form'

app/views/roles/show.html.slim
p#notice = notice

p
  strong Name:
  = @role.name
p
  strong Description:
  = @role.description

=> link_to 'Edit', edit_role_path(@role)
'|
=< link_to 'Back', roles_path