config/routes.rb
Rails.application.routes.draw do
  resources :menus
  root to: 'visitors#index'
  resources :roles do
    member do
      get 'edit_menus'
      post 'update_menus'
    end
  end
  resources :users do
    collection do
      get 'edit_profile'
      patch 'update_profile'
    end
  end
  devise_for :users, path: 'sessions'
end

app/models/role.rb
class Role < ApplicationRecord
  validates :name, presence: true

  scope :search, ->(query) { where("name like :query or description like :query", query: "%#{query}%") }

  has_many :users
  has_and_belongs_to_many :menus
end

app/views/layouts/_menu.html.slim
nav#navbarSupportedContent.nav.nav-root.flex-column.d-none.d-md-block
  -if user_signed_in?
    - Menu.roots.each do |menu|
      = render 'layouts/menu_item', menu: menu

app/views/layouts/_menu_item.html.slim
- if current_user.role.menu_ids.include? menu.id
  =link_to menu.label, menu.url, class: 'nav-link'
nav.nav.flex-column
  -menu.submenus.each do |submenu|
    = render 'layouts/menu_item', menu: submenu

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 4.0
.container-fluid
  nav.navbar.navbar-expand-lg.navbar-light.bg-light
    button.navbar-toggler.mr-2 aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
      span.navbar-toggler-icon
    a.navbar-brand href="/"  HOME
    ul.navbar-nav.ml-auto
      -if user_signed_in?
        li.nav-item.dropdown
          a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            i.fas.fa-user.mr-2
            = current_user.name
          .dropdown-menu.dropdown-menu-right aria-labelledby="navbarDropdown"
            =link_to edit_profile_users_path, class: 'dropdown-item' do
              i.fas.fa-user.mr-1
              = I18n.t "nav.profile"
            =link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do
              i.fas.fa-sign-out-alt.mr-2
              = I18n.t "nav.signout"
      -else
        li.nav-item
          = link_to new_user_session_path, class: 'nav-link' do
            i.fas.fa-sign-in-alt.mr-2
            = I18n.t "nav.signin"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'App Demo'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'App Demo'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main.py-2[role="main"]
      .row
        .col-md-2.col-sm-12
          == render 'layouts/menu'
        .col-md-10.col-sm-12.px-5
          == render 'layouts/messages'
          == yield